### ISSUE TITLE
Is this hardware support V2 analog's Z80 firmware?

### ISSUE THREAD

**Issue by griffin9k** [Retrotink/Apple-II-VGA#4]
Can I flash the Z80 firmware directly into the RPI pico to enable the Z80 function?

**Comment by Retrotink** [comment]
The V2 CPLD is not on this card so no

**Comment by griffin9k** [comment]
> The V2 CPLD is not on this card so no

Thanks

**Comment by Hubidrei** [comment]
Is the version with PAL-chip able to run CP/M?
Do i have to reprogram the PAL to run CP/M?
